# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libgdal1-dev
      - libproj-dev

before_install:
  - R -q -e 'remotes::install_github("ropensci/USAboundariesData"); print(tic::dsl_load()); tic::prepare_all_stages()'
